### ISSUE TITLE
[BUG][PAM] Index pointers stop functioning when arms are extended

### ISSUE THREAD

**Issue by Timtee** [SDraw/ml_mods_cvr#7]
Dunno how long this bug has been around for SDraw, but uh... Essentially, when one extends either arm, that arm's respective index pointer stops functioning correctly and only sometimes interacts with stuff, but often only ever on avatars, and not props. It be something worth looking into and fixing.

**Comment by SDraw** [comment]
Issue resolved: Avatar animator's update mode was set to `Animate physics`, when it should be set to `Normal`.
